#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := MPU6050.cpp servo.cpp PWM_signal.cpp line.cpp rectangle.cpp player.cpp

# header files in this project
HEADERS := MPU6050.hpp servo.hpp PWM_signal.hpp line.hpp rectangle.hpp player.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
